name: CI/CD Pipeline with Helm Chart

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
    types: [ closed ]

jobs:
  build-push-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: self-hosted
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: CI - Compilar y publicar imagen del Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend
          push: true
          tags: |
            ulisestec/frontend:latest
            ulisestec/frontend:${{ github.sha }}

      - name: Preparar dependencias de Helm
        run: helm dependency build ./helm-chart

      - name: CD - Desplegar en Kubernetes usando Helm Chart
        run: helm upgrade --install online-boutique ./helm-chart
