name: Build, Push and Deploy to Local Cluster

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-push-deploy:
    runs-on: self-hosted
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compilar y publicar imagen del Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend
          push: true
          tags: |
            ulisestec/frontend:latest
            ulisestec/frontend:${{ github.sha }}

      - name: Desplegar directamente al clúster local
        run: |
          kubectl set image deployment/frontend server=ulisestec/frontend:latest
          kubectl rollout status deployment/frontend
